
const enum State {
    'ALABAMA',
    'ALASKA',
    'ARIZONA',
    'ARKANSAS',
    'CALIFORNIA',
    'COLORADO',
    'CONNECTICUT',
    'DELAWARE',
    'FLORIDA',
    'GEORGIA',
    'HAWAII',
    'IDAHO',
    'ILLINOIS',
    'INDIANA',
    'IOWA',
    'KANSAS',
    'KENTUCKY',
    'LOUISIANA',
    'MAINE',
    'MARYLAND',
    'MASSACHUSETTS',
    'MICHIGAN',
    'MINNESOTA',
    'MISSISSIPPI',
    'MISSOURI',
    'MONTANA',
    'NEBRASKA',
    'NEVADA',
    'NEW_HAMPSHIRE',
    'NEW_JERSEY',
    'NEW_MEXICO',
    'NEW_YORK',
    'NORTH_CAROLINA',
    'NORTH_DAKOTA',
    'OHIO',
    'OKLAHOMA',
    'OREGON',
    'PENNSYLVANIA',
    'RHODE_ISLAND',
    'SOUTH_CAROLINA',
    'SOUTH_DAKOTA',
    'TENNESSEE',
    'TEXAS',
    'UTAH',
    'VERMONT',
    'VIRGINIA',
    'WASHINGTON',
    'WEST_VIRGINIA',
    'WISCONSIN',
    'WYOMING',
    'DISTRICT_OF_COLUMBIA'

};
export class Address {
    constructor(
        public id?: number,
        public streetAddress1?: string,
        public streetAddress2?: string,
        public city?: string,
        public state?: State,
        public postalCode?: string,
    ) {
    }
}
