INSERT INTO USER_ORG (USER_ID, ORG_ID) VALUES (1, 1);
INSERT INTO USER_ORG (USER_ID, ORG_ID) VALUES (3, 1);
INSERT INTO USER_ORG (USER_ID, ORG_ID) VALUES (1, 2);
INSERT INTO USER_ORG (USER_ID, ORG_ID) VALUES (3, 2);
INSERT INTO USER_ORG (USER_ID, ORG_ID) VALUES (4, 2);
INSERT INTO USER_ORG (USER_ID, ORG_ID) VALUES (3, 3);
INSERT INTO USER_ORG (USER_ID, ORG_ID) VALUES (4, 3);
