INSERT INTO ADDRESS (CITY, POSTAL_CODE, STATE, STREET_ADDRESS_1, STREET_ADDRESS_2) VALUES ('Springfield', '62776', 'ILLINOIS', '9 Shelley Pass', '379');
INSERT INTO ADDRESS (CITY, POSTAL_CODE, STATE, STREET_ADDRESS_1, STREET_ADDRESS_2) VALUES ('Burbank', '91520', 'CALIFORNIA', '6 Magdeline Trail', '9930');
INSERT INTO ADDRESS (CITY, POSTAL_CODE, STATE, STREET_ADDRESS_1, STREET_ADDRESS_2) VALUES ('Young America', '55564', 'MINNESOTA', '57 Cambridge Junction', '');
INSERT INTO ADDRESS (CITY, POSTAL_CODE, STATE, STREET_ADDRESS_1, STREET_ADDRESS_2) VALUES ('Charleston', '25331', 'WEST_VIRGINIA', '9898 Riverside Place', '63376');
