INSERT INTO SESSION (ACTIVE, DESCRIPTION, END_DATE, NAME, START_DATE, ORGANIZATION_ID) VALUES (true, null, null, 'Winter 2016', null, 1);
INSERT INTO SESSION (ACTIVE, DESCRIPTION, END_DATE, NAME, START_DATE, ORGANIZATION_ID) VALUES (false, null, null, 'Summer 2015', null, 2);
INSERT INTO SESSION (ACTIVE, DESCRIPTION, END_DATE, NAME, START_DATE, ORGANIZATION_ID) VALUES (true, null, null, 'Ongoing', null, 1);
INSERT INTO SESSION (ACTIVE, DESCRIPTION, END_DATE, NAME, START_DATE, ORGANIZATION_ID) VALUES (false, null, null, 'Summer 2017', null, 3);
