INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ADMIN');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_INSTRUCTOR');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_ORG_ADMIN');
INSERT INTO AUTHORITY (NAME) VALUES ('ROLE_STUDENT');
