CREATE TABLE ACHIEVEMENT
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_697CAC18_4F60_49C8_9A16_D59E8F4857EB) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BADGE_URL varchar(200),
    DESCRIPTION varchar(200),
    NAME varchar(100) NOT NULL,
    STUDENT_ID bigint NOT NULL,
    MILESTONE_ID bigint,
    CONSTRAINT FK7QFAIRRKNHXCG8NHFRWCN611O FOREIGN KEY (STUDENT_ID) REFERENCES USER (ID),
    CONSTRAINT FKJLIHJGM4OTKGNWCE7SDMANE3D FOREIGN KEY (MILESTONE_ID) REFERENCES MILESTONE (ID)
);
CREATE TABLE ADDRESS
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_30F65683_6579_4000_924F_5F8B5A19F402) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CITY varchar(50) NOT NULL,
    POSTAL_CODE varchar(10) NOT NULL,
    STATE varchar(255) NOT NULL,
    STREET_ADDRESS_1 varchar(50) NOT NULL,
    STREET_ADDRESS_2 varchar(50)
);
CREATE TABLE AUTHORITY
(
    NAME varchar(50) PRIMARY KEY NOT NULL
);
CREATE TABLE COURSE
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_39B61BD3_FB34_4930_B731_F2B3A4403E8B) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(200),
    START_DATE timestamp,
    END_DATE timestamp,
    INSTRUCTOR_ID bigint NOT NULL,
    PROGRAM_ID bigint NOT NULL,
    CONSTRAINT FKC0XLS9E7UQC9O08AE0T2YWR6N FOREIGN KEY (INSTRUCTOR_ID) REFERENCES USER (ID),
    CONSTRAINT FKKRT3DMA7RUV45LSAFB5LU5X7R FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM (ID)
);
CREATE TABLE COURSE_LINK
(
    COURSE_ID bigint NOT NULL,
    LINK_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_7 PRIMARY KEY (COURSE_ID, LINK_ID),
    CONSTRAINT FKJ01JE4E8EWN2FHJMBAVX2DAOM FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID),
    CONSTRAINT FKQV5L2IW1VYUT7QS8SF946EA4Y FOREIGN KEY (LINK_ID) REFERENCES ITEM_LINK (ID)
);
CREATE TABLE DATABASECHANGELOG
(
    ID varchar(255) NOT NULL,
    AUTHOR varchar(255) NOT NULL,
    FILENAME varchar(255) NOT NULL,
    DATEEXECUTED timestamp NOT NULL,
    ORDEREXECUTED integer NOT NULL,
    EXECTYPE varchar(10) NOT NULL,
    MD5SUM varchar(35),
    DESCRIPTION varchar(255),
    COMMENTS varchar(255),
    TAG varchar(255),
    LIQUIBASE varchar(20),
    CONTEXTS varchar(255),
    LABELS varchar(255),
    DEPLOYMENT_ID varchar(10)
);
CREATE TABLE DATABASECHANGELOGLOCK
(
    ID integer PRIMARY KEY NOT NULL,
    LOCKED boolean NOT NULL,
    LOCKGRANTED timestamp,
    LOCKEDBY varchar(255)
);
CREATE TABLE ITEM_LINK
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_BFAAA0B8_1493_47D3_A44F_BD9A10482FF5) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPTION varchar(200),
    ITEM_URL varchar(200) NOT NULL,
    NAME varchar(100) NOT NULL,
    THUMBNAIL_IMAGE_URL varchar(200) NOT NULL
);
CREATE TABLE MILESTONE
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_0B985D94_40A7_4044_918E_64A3E45CD3F1) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPTION varchar(200),
    NAME varchar(100) NOT NULL,
    POINTS integer,
    COURSE_ID bigint,
    CONSTRAINT FK3F014A45CX5C8Q96926161OQY FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID)
);
CREATE TABLE MILESTONE_LINK
(
    MILESTONE_ID bigint NOT NULL,
    LINK_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_D PRIMARY KEY (MILESTONE_ID, LINK_ID),
    CONSTRAINT FK8H5YKFBPXILUT9NN7A3XUI0M5 FOREIGN KEY (MILESTONE_ID) REFERENCES MILESTONE (ID),
    CONSTRAINT FKGOC8J2NP4R346A475B72QVQFH FOREIGN KEY (LINK_ID) REFERENCES ITEM_LINK (ID)
);
CREATE TABLE OAUTH_ACCESS_TOKEN
(
    TOKEN_ID varchar(255),
    TOKEN blob,
    AUTHENTICATION_ID varchar(255) PRIMARY KEY NOT NULL,
    USER_NAME varchar(50),
    CLIENT_ID varchar(255),
    AUTHENTICATION blob,
    REFRESH_TOKEN varchar(255),
    CONSTRAINT FK_OAUTH_ACCESS_TOKEN_USERNAME FOREIGN KEY (USER_NAME) REFERENCES USER (LOGIN)
);
CREATE TABLE OAUTH_APPROVALS
(
    USERID varchar(255),
    CLIENTID varchar(255),
    SCOPE varchar(255),
    STATUS varchar(255),
    EXPIRESAT timestamp,
    LASTMODIFIEDAT timestamp
);
CREATE TABLE OAUTH_CLIENT_DETAILS
(
    CLIENT_ID varchar(255) PRIMARY KEY NOT NULL,
    RESOURCE_IDS varchar(255),
    CLIENT_SECRET varchar(255),
    SCOPE varchar(255),
    AUTHORIZED_GRANT_TYPES varchar(255),
    WEB_SERVER_REDIRECT_URI varchar(255),
    AUTHORITIES varchar(255),
    ACCESS_TOKEN_VALIDITY integer,
    REFRESH_TOKEN_VALIDITY integer,
    ADDITIONAL_INFORMATION varchar(4000),
    AUTOAPPROVE varchar(4000)
);
CREATE TABLE OAUTH_CLIENT_TOKEN
(
    TOKEN_ID varchar(255),
    TOKEN blob,
    AUTHENTICATION_ID varchar(255),
    USER_NAME varchar(50),
    CLIENT_ID varchar(255),
    CONSTRAINT FK_OAUTH_CLIENT_TOKEN_USERNAME FOREIGN KEY (USER_NAME) REFERENCES USER (LOGIN)
);
CREATE TABLE OAUTH_CODE
(
    CODE varchar(255),
    AUTHENTICATION blob
);
CREATE TABLE OAUTH_REFRESH_TOKEN
(
    TOKEN_ID varchar(255),
    TOKEN blob,
    AUTHENTICATION blob
);
CREATE TABLE ORGANIZATION
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_9D3FBF25_7C2B_4348_8E48_1F6F73587698) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPTION varchar(800),
    NAME varchar(100) NOT NULL
);
CREATE TABLE PERSISTENT_AUDIT_EVENT
(
    EVENT_ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_E7DCC7F6_A367_4B6F_A959_463C3C8CD1ED) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    EVENT_DATE timestamp,
    EVENT_TYPE varchar(255),
    PRINCIPAL varchar(255) NOT NULL
);
CREATE TABLE PERSISTENT_AUDIT_EVT_DATA
(
    EVENT_ID bigint NOT NULL,
    VALUE varchar(255),
    NAME varchar(255) NOT NULL,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (EVENT_ID, NAME),
    CONSTRAINT FK9YNVWLU7W4UQPJLXVK9KISCQS FOREIGN KEY (EVENT_ID) REFERENCES PERSISTENT_AUDIT_EVENT (EVENT_ID)
);
CREATE TABLE PORTFOLIO
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_4579C1F9_069B_478E_B9C1_45490B94F2F8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    STUDENT_ID bigint NOT NULL,
    CONSTRAINT FK3HQ9RU17VF9CKR196BBNNWMC6 FOREIGN KEY (STUDENT_ID) REFERENCES USER (ID)
);
CREATE TABLE PORTFOLIO_ITEM
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_39D0099F_8773_448C_AEB3_36D275C265C0) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    COURSE_ID bigint,
    PORTFOLIO_ID bigint NOT NULL,
    CONSTRAINT FKJH6RL0Q0L8E92MAX94X3K6Y45 FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID),
    CONSTRAINT FKDLGPFR12WDUKODAAVOX0SQ7FV FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO (ID)
);
CREATE TABLE PORTFOLIO_ITEM_RESOURCE
(
    PORTFOLIO_ITEMS_ID bigint NOT NULL,
    RESOURCES_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_B PRIMARY KEY (PORTFOLIO_ITEMS_ID, RESOURCES_ID),
    CONSTRAINT FKKS7JBFTJRRPFGM5WD6CVYWY42 FOREIGN KEY (PORTFOLIO_ITEMS_ID) REFERENCES PORTFOLIO_ITEM (ID),
    CONSTRAINT FKIH4OF9QW5PCDNL9PHUOWXS8EV FOREIGN KEY (RESOURCES_ID) REFERENCES ITEM_LINK (ID)
);
CREATE TABLE PORTFOLIO_PORTFOLIO_ITEM
(
    PORTFOLIO_ID bigint NOT NULL,
    ITEM_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (PORTFOLIO_ID, ITEM_ID),
    CONSTRAINT FKB1US8DYLOGOVAC7XGT72EVJTD FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO (ID),
    CONSTRAINT FK6N81WIV03SQUWW9064B1DF7AS FOREIGN KEY (ITEM_ID) REFERENCES PORTFOLIO_ITEM (ID)
);
CREATE TABLE PROGRAM
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_B7891795_0122_4819_9450_F0E63B628B77) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACTIVE boolean NOT NULL,
    DESCRIPTION varchar(255),
    NAME varchar(50) NOT NULL,
    SCHOOL_ID bigint,
    SESSION_ID bigint NOT NULL,
    CONSTRAINT FK5JHR25Q01R7MK61CG9J107J4Q FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (ID),
    CONSTRAINT FKSU417PHG5F1D7NG4A3F6SBK38 FOREIGN KEY (SESSION_ID) REFERENCES SESSION (ID)
);
CREATE TABLE SCHOOL
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_CB41EC93_6A98_4C36_858D_E4AD3B7B1727) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DISTRICT varchar(255),
    NAME varchar(50) NOT NULL,
    ADDRESS_ID bigint,
    CONSTRAINT FKJE7YSJH9QAMI0JC33YKM13G1D FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);
CREATE TABLE SESSION
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_11CC0B9F_A51A_476D_9C80_5220E8DEF21E) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACTIVE boolean NOT NULL,
    DESCRIPTION varchar(200),
    END_DATE timestamp,
    NAME varchar(100) NOT NULL,
    START_DATE timestamp,
    ORGANIZATION_ID bigint NOT NULL,
    CONSTRAINT FKIC1WL6C6P8JQDEHBBKI771CCH FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID)
);
CREATE TABLE SOCIAL_USER_CONNECTION
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_0FDADFE6_CB3B_4D8F_94F8_DC5A0A70918D) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACCESS_TOKEN varchar(255) NOT NULL,
    DISPLAY_NAME varchar(255),
    EXPIRE_TIME bigint,
    IMAGE_URL varchar(255),
    PROFILE_URL varchar(255),
    PROVIDER_ID varchar(255) NOT NULL,
    PROVIDER_USER_ID varchar(255) NOT NULL,
    RANK bigint NOT NULL,
    REFRESH_TOKEN varchar(255),
    SECRET varchar(255),
    USER_ID varchar(255) NOT NULL
);
CREATE TABLE STUDENT_COURSE
(
    COURSE_ID bigint NOT NULL,
    USER_ID bigint NOT NULL,
    GRADE varchar(255),
    CONSTRAINT CONSTRAINT_C PRIMARY KEY (COURSE_ID, USER_ID),
    CONSTRAINT FKEJRKH4GV8IQGMSPSANAJI90WS FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID),
    CONSTRAINT FKDJRGNJ7CEJRQ7IXFBGUYJM5U9 FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
CREATE TABLE USER
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_E4325F71_956F_4145_9463_5EC6AC13768E) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN varchar(100) NOT NULL,
    PASSWORD_HASH varchar(60),
    FIRST_NAME varchar(50),
    LAST_NAME varchar(50),
    EMAIL varchar(100),
    PHONE_NUM varchar(15),
    ADDR_ID bigint,
    IMAGE_URL varchar(256),
    ACTIVATED boolean NOT NULL,
    ACTIVATION_KEY varchar(20),
    RESET_KEY varchar(20),
    CREATED_BY varchar(50) NOT NULL,
    CREATED_DATE timestamp DEFAULT NULL NOT NULL,
    RESET_DATE timestamp,
    LAST_MODIFIED_BY varchar(50),
    LAST_MODIFIED_DATE timestamp,
    IS_14_PLUS boolean NOT NULL,
    BIOGRAPHY varchar(2000),
    CONSTRAINT FK56BCHSPM0W348FXHQD5A0LMJ3 FOREIGN KEY (ADDR_ID) REFERENCES ADDRESS (ID)
);
CREATE UNIQUE INDEX UC_USERLOGIN_COL_INDEX_2 ON USER (LOGIN);
CREATE UNIQUE INDEX UC_USEREMAIL_COL_INDEX_2 ON USER (EMAIL);
CREATE TABLE USER_AUTHORITY
(
    USER_ID bigint NOT NULL,
    AUTHORITY_NAME varchar(50) NOT NULL,
    CONSTRAINT CONSTRAINT_BC PRIMARY KEY (USER_ID, AUTHORITY_NAME),
    CONSTRAINT FKPQLSJPKYBGOS9W2SVCRI7J8XY FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CONSTRAINT FK6KTGLPL5MJOSA283RVKEN2PY5 FOREIGN KEY (AUTHORITY_NAME) REFERENCES AUTHORITY (NAME)
);
CREATE TABLE USER_ORG
(
    USER_ID bigint NOT NULL,
    ORG_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_1 PRIMARY KEY (ORG_ID, USER_ID),
    CONSTRAINT FKLRLHHFNN9RGVPVXB8AA3K2WU2 FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CONSTRAINT FKAT9IOVVG69YK90OCTIFLJ4KC9 FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION (ID)
)CREATE TABLE ACHIEVEMENT
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_697CAC18_4F60_49C8_9A16_D59E8F4857EB) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BADGE_URL varchar(200),
    DESCRIPTION varchar(200),
    NAME varchar(100) NOT NULL,
    STUDENT_ID bigint NOT NULL,
    MILESTONE_ID bigint,
    CONSTRAINT FK7QFAIRRKNHXCG8NHFRWCN611O FOREIGN KEY (STUDENT_ID) REFERENCES USER (ID),
    CONSTRAINT FKJLIHJGM4OTKGNWCE7SDMANE3D FOREIGN KEY (MILESTONE_ID) REFERENCES MILESTONE (ID)
);
CREATE TABLE ADDRESS
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_30F65683_6579_4000_924F_5F8B5A19F402) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    CITY varchar(50) NOT NULL,
    POSTAL_CODE varchar(10) NOT NULL,
    STATE varchar(255) NOT NULL,
    STREET_ADDRESS_1 varchar(50) NOT NULL,
    STREET_ADDRESS_2 varchar(50)
);
CREATE TABLE AUTHORITY
(
    NAME varchar(50) PRIMARY KEY NOT NULL
);
CREATE TABLE COURSE
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_39B61BD3_FB34_4930_B731_F2B3A4403E8B) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME varchar(100) NOT NULL,
    DESCRIPTION varchar(200),
    START_DATE timestamp,
    END_DATE timestamp,
    INSTRUCTOR_ID bigint NOT NULL,
    PROGRAM_ID bigint NOT NULL,
    CONSTRAINT FKC0XLS9E7UQC9O08AE0T2YWR6N FOREIGN KEY (INSTRUCTOR_ID) REFERENCES USER (ID),
    CONSTRAINT FKKRT3DMA7RUV45LSAFB5LU5X7R FOREIGN KEY (PROGRAM_ID) REFERENCES PROGRAM (ID)
);
CREATE TABLE COURSE_LINK
(
    COURSE_ID bigint NOT NULL,
    LINK_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_7 PRIMARY KEY (COURSE_ID, LINK_ID),
    CONSTRAINT FKJ01JE4E8EWN2FHJMBAVX2DAOM FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID),
    CONSTRAINT FKQV5L2IW1VYUT7QS8SF946EA4Y FOREIGN KEY (LINK_ID) REFERENCES ITEM_LINK (ID)
);
CREATE TABLE DATABASECHANGELOG
(
    ID varchar(255) NOT NULL,
    AUTHOR varchar(255) NOT NULL,
    FILENAME varchar(255) NOT NULL,
    DATEEXECUTED timestamp NOT NULL,
    ORDEREXECUTED integer NOT NULL,
    EXECTYPE varchar(10) NOT NULL,
    MD5SUM varchar(35),
    DESCRIPTION varchar(255),
    COMMENTS varchar(255),
    TAG varchar(255),
    LIQUIBASE varchar(20),
    CONTEXTS varchar(255),
    LABELS varchar(255),
    DEPLOYMENT_ID varchar(10)
);
CREATE TABLE DATABASECHANGELOGLOCK
(
    ID integer PRIMARY KEY NOT NULL,
    LOCKED boolean NOT NULL,
    LOCKGRANTED timestamp,
    LOCKEDBY varchar(255)
);
CREATE TABLE ITEM_LINK
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_BFAAA0B8_1493_47D3_A44F_BD9A10482FF5) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPTION varchar(200),
    ITEM_URL varchar(200) NOT NULL,
    NAME varchar(100) NOT NULL,
    THUMBNAIL_IMAGE_URL varchar(200) NOT NULL
);
CREATE TABLE MILESTONE
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_0B985D94_40A7_4044_918E_64A3E45CD3F1) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPTION varchar(200),
    NAME varchar(100) NOT NULL,
    POINTS integer,
    COURSE_ID bigint,
    CONSTRAINT FK3F014A45CX5C8Q96926161OQY FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID)
);
CREATE TABLE MILESTONE_LINK
(
    MILESTONE_ID bigint NOT NULL,
    LINK_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_D PRIMARY KEY (MILESTONE_ID, LINK_ID),
    CONSTRAINT FK8H5YKFBPXILUT9NN7A3XUI0M5 FOREIGN KEY (MILESTONE_ID) REFERENCES MILESTONE (ID),
    CONSTRAINT FKGOC8J2NP4R346A475B72QVQFH FOREIGN KEY (LINK_ID) REFERENCES ITEM_LINK (ID)
);
CREATE TABLE OAUTH_ACCESS_TOKEN
(
    TOKEN_ID varchar(255),
    TOKEN blob,
    AUTHENTICATION_ID varchar(255) PRIMARY KEY NOT NULL,
    USER_NAME varchar(50),
    CLIENT_ID varchar(255),
    AUTHENTICATION blob,
    REFRESH_TOKEN varchar(255),
    CONSTRAINT FK_OAUTH_ACCESS_TOKEN_USERNAME FOREIGN KEY (USER_NAME) REFERENCES USER (LOGIN)
);
CREATE TABLE OAUTH_APPROVALS
(
    USERID varchar(255),
    CLIENTID varchar(255),
    SCOPE varchar(255),
    STATUS varchar(255),
    EXPIRESAT timestamp,
    LASTMODIFIEDAT timestamp
);
CREATE TABLE OAUTH_CLIENT_DETAILS
(
    CLIENT_ID varchar(255) PRIMARY KEY NOT NULL,
    RESOURCE_IDS varchar(255),
    CLIENT_SECRET varchar(255),
    SCOPE varchar(255),
    AUTHORIZED_GRANT_TYPES varchar(255),
    WEB_SERVER_REDIRECT_URI varchar(255),
    AUTHORITIES varchar(255),
    ACCESS_TOKEN_VALIDITY integer,
    REFRESH_TOKEN_VALIDITY integer,
    ADDITIONAL_INFORMATION varchar(4000),
    AUTOAPPROVE varchar(4000)
);
CREATE TABLE OAUTH_CLIENT_TOKEN
(
    TOKEN_ID varchar(255),
    TOKEN blob,
    AUTHENTICATION_ID varchar(255),
    USER_NAME varchar(50),
    CLIENT_ID varchar(255),
    CONSTRAINT FK_OAUTH_CLIENT_TOKEN_USERNAME FOREIGN KEY (USER_NAME) REFERENCES USER (LOGIN)
);
CREATE TABLE OAUTH_CODE
(
    CODE varchar(255),
    AUTHENTICATION blob
);
CREATE TABLE OAUTH_REFRESH_TOKEN
(
    TOKEN_ID varchar(255),
    TOKEN blob,
    AUTHENTICATION blob
);
CREATE TABLE ORGANIZATION
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_9D3FBF25_7C2B_4348_8E48_1F6F73587698) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPTION varchar(800),
    NAME varchar(100) NOT NULL
);
CREATE TABLE PERSISTENT_AUDIT_EVENT
(
    EVENT_ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_E7DCC7F6_A367_4B6F_A959_463C3C8CD1ED) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    EVENT_DATE timestamp,
    EVENT_TYPE varchar(255),
    PRINCIPAL varchar(255) NOT NULL
);
CREATE TABLE PERSISTENT_AUDIT_EVT_DATA
(
    EVENT_ID bigint NOT NULL,
    VALUE varchar(255),
    NAME varchar(255) NOT NULL,
    CONSTRAINT CONSTRAINT_4 PRIMARY KEY (EVENT_ID, NAME),
    CONSTRAINT FK9YNVWLU7W4UQPJLXVK9KISCQS FOREIGN KEY (EVENT_ID) REFERENCES PERSISTENT_AUDIT_EVENT (EVENT_ID)
);
CREATE TABLE PORTFOLIO
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_4579C1F9_069B_478E_B9C1_45490B94F2F8) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    STUDENT_ID bigint NOT NULL,
    CONSTRAINT FK3HQ9RU17VF9CKR196BBNNWMC6 FOREIGN KEY (STUDENT_ID) REFERENCES USER (ID)
);
CREATE TABLE PORTFOLIO_ITEM
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_39D0099F_8773_448C_AEB3_36D275C265C0) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    COURSE_ID bigint,
    PORTFOLIO_ID bigint NOT NULL,
    CONSTRAINT FKJH6RL0Q0L8E92MAX94X3K6Y45 FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID),
    CONSTRAINT FKDLGPFR12WDUKODAAVOX0SQ7FV FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO (ID)
);
CREATE TABLE PORTFOLIO_ITEM_RESOURCE
(
    PORTFOLIO_ITEMS_ID bigint NOT NULL,
    RESOURCES_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_B PRIMARY KEY (PORTFOLIO_ITEMS_ID, RESOURCES_ID),
    CONSTRAINT FKKS7JBFTJRRPFGM5WD6CVYWY42 FOREIGN KEY (PORTFOLIO_ITEMS_ID) REFERENCES PORTFOLIO_ITEM (ID),
    CONSTRAINT FKIH4OF9QW5PCDNL9PHUOWXS8EV FOREIGN KEY (RESOURCES_ID) REFERENCES ITEM_LINK (ID)
);
CREATE TABLE PORTFOLIO_PORTFOLIO_ITEM
(
    PORTFOLIO_ID bigint NOT NULL,
    ITEM_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_8 PRIMARY KEY (PORTFOLIO_ID, ITEM_ID),
    CONSTRAINT FKB1US8DYLOGOVAC7XGT72EVJTD FOREIGN KEY (PORTFOLIO_ID) REFERENCES PORTFOLIO (ID),
    CONSTRAINT FK6N81WIV03SQUWW9064B1DF7AS FOREIGN KEY (ITEM_ID) REFERENCES PORTFOLIO_ITEM (ID)
);
CREATE TABLE PROGRAM
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_B7891795_0122_4819_9450_F0E63B628B77) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACTIVE boolean NOT NULL,
    DESCRIPTION varchar(255),
    NAME varchar(50) NOT NULL,
    SCHOOL_ID bigint,
    SESSION_ID bigint NOT NULL,
    CONSTRAINT FK5JHR25Q01R7MK61CG9J107J4Q FOREIGN KEY (SCHOOL_ID) REFERENCES SCHOOL (ID),
    CONSTRAINT FKSU417PHG5F1D7NG4A3F6SBK38 FOREIGN KEY (SESSION_ID) REFERENCES SESSION (ID)
);
CREATE TABLE SCHOOL
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_CB41EC93_6A98_4C36_858D_E4AD3B7B1727) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DISTRICT varchar(255),
    NAME varchar(50) NOT NULL,
    ADDRESS_ID bigint,
    CONSTRAINT FKJE7YSJH9QAMI0JC33YKM13G1D FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);
CREATE TABLE SESSION
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_11CC0B9F_A51A_476D_9C80_5220E8DEF21E) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACTIVE boolean NOT NULL,
    DESCRIPTION varchar(200),
    END_DATE timestamp,
    NAME varchar(100) NOT NULL,
    START_DATE timestamp,
    ORGANIZATION_ID bigint NOT NULL,
    CONSTRAINT FKIC1WL6C6P8JQDEHBBKI771CCH FOREIGN KEY (ORGANIZATION_ID) REFERENCES ORGANIZATION (ID)
);
CREATE TABLE SOCIAL_USER_CONNECTION
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_0FDADFE6_CB3B_4D8F_94F8_DC5A0A70918D) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    ACCESS_TOKEN varchar(255) NOT NULL,
    DISPLAY_NAME varchar(255),
    EXPIRE_TIME bigint,
    IMAGE_URL varchar(255),
    PROFILE_URL varchar(255),
    PROVIDER_ID varchar(255) NOT NULL,
    PROVIDER_USER_ID varchar(255) NOT NULL,
    RANK bigint NOT NULL,
    REFRESH_TOKEN varchar(255),
    SECRET varchar(255),
    USER_ID varchar(255) NOT NULL
);
CREATE TABLE STUDENT_COURSE
(
    COURSE_ID bigint NOT NULL,
    USER_ID bigint NOT NULL,
    GRADE varchar(255),
    CONSTRAINT CONSTRAINT_C PRIMARY KEY (COURSE_ID, USER_ID),
    CONSTRAINT FKEJRKH4GV8IQGMSPSANAJI90WS FOREIGN KEY (COURSE_ID) REFERENCES COURSE (ID),
    CONSTRAINT FKDJRGNJ7CEJRQ7IXFBGUYJM5U9 FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);
CREATE TABLE USER
(
    ID bigint DEFAULT (NEXT VALUE FOR SYSTEM_SEQUENCE_E4325F71_956F_4145_9463_5EC6AC13768E) AUTO_INCREMENT PRIMARY KEY NOT NULL,
    LOGIN varchar(100) NOT NULL,
    PASSWORD_HASH varchar(60),
    FIRST_NAME varchar(50),
    LAST_NAME varchar(50),
    EMAIL varchar(100),
    PHONE_NUM varchar(15),
    ADDR_ID bigint,
    IMAGE_URL varchar(256),
    ACTIVATED boolean NOT NULL,
    ACTIVATION_KEY varchar(20),
    RESET_KEY varchar(20),
    CREATED_BY varchar(50) NOT NULL,
    CREATED_DATE timestamp DEFAULT NULL NOT NULL,
    RESET_DATE timestamp,
    LAST_MODIFIED_BY varchar(50),
    LAST_MODIFIED_DATE timestamp,
    IS_14_PLUS boolean NOT NULL,
    BIOGRAPHY varchar(2000),
    CONSTRAINT FK56BCHSPM0W348FXHQD5A0LMJ3 FOREIGN KEY (ADDR_ID) REFERENCES ADDRESS (ID)
);
CREATE UNIQUE INDEX UC_USERLOGIN_COL_INDEX_2 ON USER (LOGIN);
CREATE UNIQUE INDEX UC_USEREMAIL_COL_INDEX_2 ON USER (EMAIL);
CREATE TABLE USER_AUTHORITY
(
    USER_ID bigint NOT NULL,
    AUTHORITY_NAME varchar(50) NOT NULL,
    CONSTRAINT CONSTRAINT_BC PRIMARY KEY (USER_ID, AUTHORITY_NAME),
    CONSTRAINT FKPQLSJPKYBGOS9W2SVCRI7J8XY FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CONSTRAINT FK6KTGLPL5MJOSA283RVKEN2PY5 FOREIGN KEY (AUTHORITY_NAME) REFERENCES AUTHORITY (NAME)
);
CREATE TABLE USER_ORG
(
    USER_ID bigint NOT NULL,
    ORG_ID bigint NOT NULL,
    CONSTRAINT CONSTRAINT_1 PRIMARY KEY (ORG_ID, USER_ID),
    CONSTRAINT FKLRLHHFNN9RGVPVXB8AA3K2WU2 FOREIGN KEY (USER_ID) REFERENCES USER (ID),
    CONSTRAINT FKAT9IOVVG69YK90OCTIFLJ4KC9 FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION (ID)
)
